language: shell

os:
  - windows
  - linux
  
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install miniconda3;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
    fi
  - conda update -q conda
  
install:
  - travis_retry conda install -y python=3.6 conda-build anaconda-client conda-verify
  
script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then build-ffmpeg.bat; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ./build-ffmpeg.sh; fi
    
after_success: # Nothing to do
