{% set name = "ffmpeg-python" %}
{% set version = "0.1.16" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 721db04120ad110619c17dd7a72db8d21a6738d721be1b3b4c72a7516e6b07f4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  build:
    - future
    - pip
    - setuptools
    - python
    - pytest-runner
  run:
    - future
    - python

about:
  home: https://github.com/kkroening/ffmpeg-python
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: Python bindings for FFmpeg - with complex filtering support
  doc_url: https://kkroening.github.io/ffmpeg-python/
