{% set name = "ffmpeg" %}
{% set version = "4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: {{ name }}-release-64bit-static.tar.xz  # [not win]
  url: https://johnvansickle.com/ffmpeg/releases/{{ name }}-release-64bit-static.tar.xz  # [not win]
  sha256: 47b0d0cfd43e16f33e566832c1c78063d62e90aa217997573105eccc93327239  # [not win]

test:
  commands:
    - ffmpeg -version  # [not win]
    - ffmpeg.exe -version  # [win]

about:
  home: http://www.ffmpeg.org/
  license: GPL 3
  summary: Cross-platform solution to record, convert and stream audio and video.
