{% set name = "ffmpeg" %}
{% set version = "4.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}-win64-static.zip  # [win]
  url: https://ffmpeg.zeranoe.com/builds/win64/static/{{ name }}-{{ version }}-win64-static.zip  # [win]
  sha256: 2bf3726d7b489f1fe5609e1f9d93d827fd9e9c9d21b829b254a5bae0c3f60ec8  # [win]

  fn: {{ name }}-release-64bit-static.tar.xz  # [not win]
  url: https://johnvansickle.com/ffmpeg/releases/{{ name }}-release-64bit-static.tar.xz  # [not win]
  sha256: 6967b1f475b4f121e829d09a1d586d6e31e5cc6fdfe2dc890fa1a998dbb0bdf7  # [not win]

test:
  commands:
    - ffmpeg -version  # [not win]
    - ffmpeg.exe -version  # [win]

about:
  home: http://www.ffmpeg.org/
  license: GPL 3
  summary: Cross-platform solution to record, convert and stream audio and video.
